experiment_name: rtklib_brdc
ppp_solution: rtklib # either 'rt_ppp' or 'rtklib'
#ppp_executable: rnx2rtkp #./rt_ppp.exe or rnx2rtkp
ppp_executable: docker run -v ${PWD}/data:/data rtklib
ppp_template_conf: templates/rtklib_template_brdc.conf
run_folder: ./data
end_year: 2015
start_year: 2015
station: onrj
reference_position: [4283638.3610, -4026028.8230, -2466096.8370] #the PPP is going to start with this coordinate and errors are computed against it.
save_array_as: onrj_rtklib_brdc.npy
ionex_pattern: codg{doy:03}0.{year%100}i.Z #optional, only for GIM-based ppp
