experiment_name: rtklib_brdc
# Running folder
run_folder: data
# ppp_solution can be either 'rt_ppp' or 'rtklib'
ppp_solution: rtklib
# ppp_executable can be set for linux, windows or docker
# for linux: rnx2rtkp or rt_ppp
# for windows: ./rnx2rtkp.exe or ./rt_ppp.exe
# for docker: docker run -v ${PWD}/{run_folder}:/data rtklib
ppp_executable: docker run -v ${PWD}/data:/data rtklib:demo5
# Template file
ppp_template_conf: templates/rtklib_template_brdc.conf
# Start and End dates
start_date: 2015-01-04 # YYYY-MM-DD
end_date: 2015-12-31 # YYYY-MM-DD
# Station to be processed
station: onrj
# Reference position which PPP will use to start processing and to compute errors against it.
reference_position: [4283638.3610, -4026028.8230, -2466096.8370]
# Save results as numpy
save_array_as: data/rtklib_brdc/onrj.npy
# Optional ionex pattern. Used only for GIM-based ppp
ionex_pattern: codg{doy:03}0.{year%100}i.Z
